<?php

namespace AppBundle\Repository;

/**
 * RegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends \Doctrine\ORM\EntityRepository
{
    public function countStudents()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(r.id)  FROM AppBundle:Registration r WHERE r.status = :student'
            )
            ->setParameter('student', 'Student')
            ->getSingleScalarResult();
    }
    public function countTalks()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(r.id)  FROM AppBundle:Registration r WHERE r.title IS NOT NULL'
            )
            ->getSingleScalarResult();
    }
    public function countRecommendation()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(r.id)  FROM AppBundle:Registration r WHERE r.file IS NOT NULL'
            )
            ->getSingleScalarResult();
    }
    public function countFellowships()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(r.id)  FROM AppBundle:Registration r WHERE r.fellowship = true'
            )
            ->getSingleScalarResult();
    }

}
